services:
  db:
    build:
      context: ..
      dockerfile: docker/database.Dockerfile
    container_name: db
    env_file:
      - ../database/.env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - project_net

  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: backend
    depends_on:
      - db
    env_file:
      - ../backend/prisma/.env
    ports:
      - "3001:3000"
    networks:
      - project_net

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8081:80"
    networks:
      - project_net

volumes:
  db_data:

networks:
  project_net:
    driver: bridge
